name: Deploy to Ubuntu Server

on:
  workflow_dispatch:
#   push:
#     branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      # - name: Copy files to server
      #   run: |
      #     rsync -avz --exclude=node_modules --exclude=.git ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/volodymyr/projects/backend/pdf

      - name: Build and run Docker on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/volodymyr/projects/backend/pdf
            docker compose down
            docker system prune -af
            docker-compose build --no-cache
            docker compose up --build -d
          EOF