name: Deploy to Ubuntu Server test

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync project files to server
        run: |
          rsync -avz --exclude=node_modules --exclude=.git -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/volodymyr/projects/backend/pdf

      - name: Run Docker Compose on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/volodymyr/projects/backend/pdf
            docker compose down
            docker system prune -af --volumes --force
            docker compose build --no-cache
            docker compose up --build -d
          EOF
